# Generated by Django 3.1.7 on 2022-05-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('number_plate', models.CharField(max_length=20)),
                ('type_of_vehicle', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
