# Generated by Django 4.0.4 on 2022-05-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_charge_registartion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('number_plate', models.CharField(max_length=20)),
                ('type_of_vehicle', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationDetails',
        ),
    ]
